### ISSUE TITLE
I need some help, can you help me?

### ISSUE THREAD

**Issue by Caiop23** [amWilq/Yupoo-PhotoDownloader#1]
Hi. I'm new to the community. wanted an explanation of how to run YupooDownloader. I'm not getting. need help.

**Comment by amWilq** [comment]
Hi!
Nice to see someone found it! Do you have already installed Python 3.x?

**Comment by Caiop23** [comment]
Yes. My python Version 3.9, 
I don't know much about python. Can you make a video on how to download yupoo?

**Comment by amWilq** [comment]
1. Download YupooDownloader.
2. Open cmd in the same folder where you downloaded it and type "pip install -r Requirements.txt"
3. Go to file "UZUPELNIJ.json" and type link for yupoo 
4. Open again cmd and type "python YupooPhotoDownloader.py"

**Comment by Caiop23** [comment]
Error.


![image](https://user-images.githubusercontent.com/84137690/118300172-05401500-b4b8-11eb-8853-a523561e32f3.png)

**Comment by amWilq** [comment]
fixed file 'requirements.txt' try now

**Comment by Caiop23** [comment]
requirements.txt has been installed. Now imports panda not working
thank you so much for your attention i'm learning from you.

![image](https://user-images.githubusercontent.com/84137690/118302000-12f69a00-b4ba-11eb-9a4a-da5b416c5614.png)

**Comment by amWilq** [comment]
pip install pandas

**Comment by amWilq** [comment]
It works now?

**Comment by Caiop23** [comment]
No. i can't.

**Comment by amWilq** [comment]
What error now you have?

**Comment by Caiop23** [comment]
![image](https://user-images.githubusercontent.com/84137690/118366449-a68da080-b576-11eb-9685-3f6b7cb202da.png)

this

**Comment by amWilq** [comment]
make file 'bf3_strona.csv' then try again

**Comment by Caiop23** [comment]
run .py generate this bf3_strona


![image](https://user-images.githubusercontent.com/84137690/118366995-eeacc300-b576-11eb-93e5-23730ec9d5f8.png)

**Comment by amWilq** [comment]
try remove 17 line of code "os.system("attrib +h bf3_strona.csv")"

**Comment by Caiop23** [comment]
how to make this file ?

**Comment by Caiop23** [comment]
Ok

**Comment by Caiop23** [comment]
Same error 
i remore line 17

**Comment by amWilq** [comment]
add  in 17 line `os.chmod('bf3_strona.csv', 0o755)`

**Comment by amWilq** [comment]
You need remove file `bf3_strona` before you strat script

**Comment by Caiop23** [comment]
i remove file, now this. 

![image](https://user-images.githubusercontent.com/84137690/118370172-e8214a00-b57c-11eb-86fe-0200f4e21b13.png)

**Comment by amWilq** [comment]
Updated fille `requirements.txt` check now

**Comment by Caiop23** [comment]
not working

**Comment by amWilq** [comment]
What now?

**Comment by Caiop23** [comment]
![image](https://user-images.githubusercontent.com/84137690/119072624-2cb84580-b9c2-11eb-873a-06e9e58b18fd.png)

**Comment by amWilq** [comment]
Changed 28 lines, check now.

**Comment by Caiop23** [comment]
This code save only url link ? or save image file jpg ?

**Comment by amWilq** [comment]
Images in jpg

**Comment by Caiop23** [comment]
where the images are saved, here for me the link is only showing in the file bf3_stronda.csv

**Comment by amWilq** [comment]
New folders should start with the `0` name. And in its folder photos should be saved

**Comment by Caiop23** [comment]
WATCH THIS VIDEO, PLEASE

https://youtu.be/AodPpVMrXRI

**Comment by Caiop23** [comment]
now working
thanks

**Comment by amWilq** [comment]
Good to hear. if you have any suggestions for changes, let me know

**Comment by Caiop23** [comment]
You could put it to create the folders with the original name of the downloaded album. Only if it is possible
